### ISSUE TITLE
Api has not returned more countries since yesterday.

### ISSUE THREAD

**Issue by joaopauloexcel** [lennertVanSever/graphcountries#19]
Message: "Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0. Caused by: Failed to establish connection in 30000ms"

**Comment by tamirisapbonicenha** [comment]
Yes, same here.

**Comment by lennertVanSever** [comment]
Thanks for reporting, after a year my free trial on Google Cloud expired. I enabled billing to bring the Neo4j server up again. The IP address of the Neo4j service changed so I had to do a redeploy. I checked the example app https://graphcountries-example-vanilla-js.netlify.app and everything works as expected.
Apologies for the downtime!
