### ISSUE TITLE
Using endpoint has SSL issue

### ISSUE THREAD

**Issue by RPlaha0390** [lennertVanSever/graphcountries#5]
Hi, 

I am trying to use this endpoint. I have tried to consume the api using the `apollo-client` library. Both do not seem to work and provide me with the following error:

<img width="704" alt="Screenshot 2020-05-23 at 14 44 17" src="https://user-images.githubusercontent.com/21662006/82732247-ee7f3c00-9d03-11ea-8cd0-881357bab4eb.png">

Bellow is my code: 

`App.tsx`

```
import React from 'react';
import './App.css';
import ViewCountries from './containers/ViewCountries';
import { ApolloProvider } from '@apollo/react-hooks';
import { ApolloClient } from 'apollo-client';
import { createHttpLink } from 'apollo-link-http';
import { ApolloLink } from 'apollo-link';
import { InMemoryCache } from 'apollo-cache-inmemory';

const httpLink = createHttpLink({
  uri: 'https://countries-274616.ew.r.appspot.com/',
});

const link = ApolloLink.from([httpLink]);

const client = new ApolloClient({
  link,
  cache: new InMemoryCache(),
});

function App() {
  return (
    <ApolloProvider client={client}>
      <ViewCountries />
    </ApolloProvider>
  );
}

export default App;
```

`ViewCountries.tsx`

```
import React from 'react';
import { useQuery } from '@apollo/react-hooks';
import gql from 'graphql-tag';

const COUNTRIES = gql`
  {
    countries {
      name
    }
  }
`;

const ViewCountries = () => {
  const { loading, error, data } = useQuery(COUNTRIES);

  return (
    <></>
  );
};

export default ViewCountries;

```

What am I doing wrong, or is it your server that does not work? 🤔 

Thank you 👍

**Comment by jbesraa** [comment]
I can access the server successfully, try without the createHttpLink

```
import ApolloClient from "apollo-boost";

export default new ApolloClient({
  uri: "https://countries-274616.ew.r.appspot.com"
});
```

**Comment by lennertVanSever** [comment]
Hi,

I added an example on how to use the API for a simple create-react-app, check it out in the [example folder](https://github.com/lennertVanSever/graphcountries/tree/master/examples/react-apollo).
The example doesn't give any SSL error, let me know if anything else goes wrong.

Cheers,
Lennert

**Comment by RPlaha0390** [comment]
@jbesraa @lennertVanSever Thanks for your reply. 

For anyone else experiencing this problem I have discovered that it had something to do with my internet provider blocking this website. I had to login and add this url to allowed list of domains I can view.
